### PR TITLE
Con 3061 20221212 update styling on conservator cli docs

### PR DESCRIPTION
**Pull request by agonzales42**
**NOTE** New package included, requires install.
Changed the styling of the CLI Guide to match that of the Getting Started Guide.
- Added fonts from the Getting Started Guide
- Created new CLI Guide logo

**File Changes:**
`requirements.txt`
- Added new package, sphinx_rtd_theme.

`docs/Makefile`
- Moved all source files to new folder, '_source' in order to build html. Without this change, build was being prevented by errors in files outside of docs.

`docs/_source/_static/fonts.css`
`docs/_source/_templates/layout.html`
- Added the layout.html and fonts from the Getting Started Guide so that fonts and styles will be applied to the CLI Guide

`docs/_source/conf.py`
- Changes to html options to reflect the html in the Getting Started Guide, including the theme.

`docs/_static/conservator-cli-guide.svg`
`docs/_static/favicon.ico`
- New logo and favicon.

`docs/_static/fonts/Industry-Book/Industry-Book.eot`
`docs/_static/fonts/Industry-Book/Industry-Book.otf`
`docs/_static/fonts/Industry-Book/Industry-Book.svg`
`docs/_static/fonts/Industry-Book/Industry-Book.woff`
`docs/_static/fonts/NunitoSans-Bold/NunitoSans-Bold.eot`
`docs/_static/fonts/NunitoSans-Bold/NunitoSans-Bold.svg`
`docs/_static/fonts/NunitoSans-Bold/NunitoSans-Bold.woff`
`docs/_static/fonts/NunitoSans-Bold/NunitoSans-Bold.woff2`
`docs/_static/fonts/NunitoSans-ExtraBold/NunitoSans-ExtraBold.eot`
`docs/_static/fonts/NunitoSans-ExtraBold/NunitoSans-ExtraBold.svg`
`docs/_static/fonts/NunitoSans-ExtraBold/NunitoSans-ExtraBold.woff`
`docs/_static/fonts/NunitoSans-ExtraBold/NunitoSans-ExtraBold.woff2`
`docs/_static/fonts/NunitoSans-Regular/NunitoSans-Regular.eot`
`docs/_static/fonts/NunitoSans-Regular/NunitoSans-Regular.svg`
`docs/_static/fonts/NunitoSans-Regular/NunitoSans-Regular.woff`
`docs/_static/fonts/NunitoSans-Regular/NunitoSans-Regular.woff2`
- Fonts

[[JIRA Task](https://jiracommercial.flir.com/browse/CON-3061)]

### CODE REVIEW

**Review by nbutler77 — CHANGES_REQUESTED** [review]
- Please move the files out of `_source`, it seems to build fine if the files are in their original locations
 - Please update the formatting so that tables auto-wrap text instead of adding scroll-bars

**Review by nbutler77 — APPROVED** [review]
Looks good to me.

**Review by rlc2 — APPROVED** [review]

**Comment by nbutler77** [comment]
@filitchp Can you take a look at this, please?

**Review by filitchp — APPROVED** [review]
Looks good! I changed the stack diagram to give a one-shot explanation of the codebase. I also made a few minor naming tweaks and directed the web link to the official landing page rather than the company instance.

**Review by nbutler77 — CHANGES_REQUESTED** [review]
@filitchp that png still doesn't look great. If you want it to be displayed at 700px wide, can you just make it that size? The font is still getting "squashed" when I look at the docs.

**Review by filitchp — APPROVED** [review]
@nbutler77 the image is 1400x805px (twice the 700px desired width for high density displays). https://raw.githubusercontent.com/FLIR/conservator-cli/1f97bf739d93a81891b0e7d1156053070c0a56c8/docs/_static/stack.png

**Comment by nbutler77** [comment]
> @nbutler77 the image is 1400x805px (twice the 700px desired width for high density displays). https://raw.githubusercontent.com/FLIR/conservator-cli/1f97bf739d93a81891b0e7d1156053070c0a56c8/docs/_static/stack.png

It doesn't matter what size the actual image is, or what resolution the screen is, it's always going to be displayed at 700px wide because that's what is specified in the source rst file.

**Review by nbutler77 — APPROVED** [review]
I spoke to Paul, and apparently the graphic looks fine on higher-resolution displays. This is good to merge as is; if users complain about the image in the documentation, we can address that later.

**Pull request merged**
