### PR TITLE
Con 2464 20220322 move collection

### PR DESCRIPTION
**Pull request by SJLC**
Implement 'move' method for Collection
    
Use new moveCollection mutation to provide a method that moves a collection into another collection

[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2441k)]

### CODE REVIEW

**Comment by SJLC** [comment]
Note this will not succeed in passing tests until CON-1519 has been deployed

**Review by nbutler77 — APPROVED** [review]
Changes look good.
Only comment would be - is there some way to get the codegen tool to sort arrays consistently so that there are not as many changes when the schema is regenerated?

**Comment by SJLC** [comment]
> Changes look good. Only comment would be - is there some way to get the codegen tool to sort arrays consistently so that there are not as many changes when the schema is regenerated?

That's a good idea -- it currently just takes the order returned by server, but we didn't realize it would end up getting reordered so often.

**Comment by SJLC** [comment]
Tests are failing because of a regression in response to `dataset.get_commit_by_id("HEAD")`
```
conservator --config=prod datasets commit 8ZtnjyYsP4sMZ2aWx HEAD
ERROR:sgqlc.endpoint.http:GraphQL query failed with 1 errors
INFO:sgqlc.endpoint.http:Error #0 gitCommit:
INFO:sgqlc.endpoint.http:   | Error Response code is undefined in gitCommitByUrl
INFO:sgqlc.endpoint.http:   -
INFO:sgqlc.endpoint.http:   | Locations:
INFO:sgqlc.endpoint.http:   |  0 | query {
INFO:sgqlc.endpoint.http:   |  1 |   gitCommit(datasetId: "8ZtnjyYsP4sMZ2aWx", commitId: "HEAD") {
INFO:sgqlc.endpoint.http:   |      --^
Traceback (most recent call last):
  File "/home/flir/work/conservator_cli_next/venv/bin/conservator", line 11, in <module>
    load_entry_point('conservator-cli', 'console_scripts', 'conservator')()
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/flir/work/conservator_cli_next/venv/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/flir/work/conservator_cli_next/FLIR/conservator/cli/managers.py", line 330, in commit_
    commit = dataset.get_commit_by_id(commit_id, fields=commit_fields)
  File "/home/flir/work/conservator_cli_next/FLIR/conservator/wrappers/dataset.py", line 265, in get_commit_by_id
    commit_id=commit_id,
  File "/home/flir/work/conservator_cli_next/FLIR/conservator/connection.py", line 178, in query
    return self._query(query, fields, **kwargs)
  File "/home/flir/work/conservator_cli_next/FLIR/conservator/connection.py", line 204, in _query
    result = self.run(op)
  File "/home/flir/work/conservator_cli_next/FLIR/conservator/connection.py", line 157, in run
    raise ConservatorGraphQLServerError(gql, errors)
FLIR.conservator.connection.ConservatorGraphQLServerError: errors='[{'message': 'Error Response code is undefined in gitCommitByUrl', 'locations': [{'line': 2, 'column': 3}], 'path': ['gitCommit'], 'correlationId': '01FYYVTTXP4E27FWJ2W8QRNBNC'}]' operation='query {
  gitCommit(datasetId: "8ZtnjyYsP4sMZ2aWx", commitId: "HEAD") {
    _id
    authorName
    authorEmail
    shortMessage
    parents
    tree
  }
}'
```

**Comment by SJLC** [comment]
> > Changes look good. Only comment would be - is there some way to get the codegen tool to sort arrays consistently so that there are not as many changes when the schema is regenerated?
> 
> That's a good idea -- it currently just takes the order returned by server, but we didn't realize it would end up getting reordered so often.

Actually this time around the server is giving back all the type enums in alphabetical order, so it is exactly the same set of changes whether or not I add a sort step for generating schema.py 

@nbutler77 can you think of any other part of the schema prone to getting resorted on the server, causing pointless code churn here?

**Comment by nbutler77** [comment]
> Actually this time around the server is giving back all the type enums in alphabetical order, so it is exactly the same set of changes whether or not I add a sort step for generating schema.py
> 
> @nbutler77 can you think of any other part of the schema prone to getting resorted on the server, causing pointless code churn here?

The input fields and type fields ordering doesn't seem to change, so I guess it's only enums. No idea why that ordering would change, since I don't believe we touched them recently, and we didn't change our Graphql packages. Could `black` or `sgqlc` have changed? I notice the `requirements.txt` file doesn't specify versions for either of them.

**Review by rlc2 — APPROVED** [review]

**Comment by SJLC** [comment]
> > Actually this time around the server is giving back all the type enums in alphabetical order, so it is exactly the same set of changes whether or not I add a sort step for generating schema.py
> > @nbutler77 can you think of any other part of the schema prone to getting resorted on the server, causing pointless code churn here?
> 
> The input fields and type fields ordering doesn't seem to change, so I guess it's only enums. No idea why that ordering would change, since I don't believe we touched them recently, and we didn't change our Graphql packages. Could `black` or `sgqlc` have changed? I notice the `requirements.txt` file doesn't specify versions for either of them.

You guessed it... apparently sgqlc started sorting, so after this churn it should stop
https://github.com/profusion/sgqlc/pull/147

**Pull request merged**
