### PR TITLE
Con 2610 20220504 update dataset annotation ap is

### PR DESCRIPTION
**Pull request by nbutler77**
Updates schema.py

**File Changes:**

`FLIR/conservator/generated/schema.py`
 - Updated schema to match latest conservator release
 - Removed `label` fields from DatasetAnnotation/Annotation - they are deprecated in Conservator

`examples/dataset_annotation_qa.py`
 - Updated query calls to match new API signature

[[JIRA Task](https://jiracommercial.flir.com/browse/CON-2610)]

### CODE REVIEW

**Comment by SJLC** [comment]
The label fields may be deprecated, but they are still in the schema. Is this manual edit is going to be needed for every schema update going forward? Why just this deprecated field? Can we leave it for now and see whether we can get rid of all use of deprecated fields, then turn off `include_deprecated` when generating schema updates?

**Comment by nbutler77** [comment]
> The label fields may be deprecated, but they are still in the schema. Is this manual edit is going to be needed for every schema update going forward? Why just this deprecated field? Can we leave it for now and see whether we can get rid of all use of deprecated fields, then turn off `include_deprecated` when generating schema updates?

I've created a task to remove deprecated fields from Conservator; leaving the label fields in place will potentially break anything to do with annotations/dataset annotations in conservator-cli, so we will need to manually remove them until we have dealt with deprecated fields in Conservator, and thus can remove the `include_deprecated` flag from the schema generation script.

Note that conservator-cli currently uses the Video.frames field, which is marked as deprecated, so that's a fairly major piece of re-work that will need to be done before we can remove that flag.

**Comment by SJLC** [comment]
Ok one more question: can the "label" query go away too, or is that needed still? It would be easier if all instances of singular "label" can go away, instead of most of them

**Comment by nbutler77** [comment]
> Ok one more question: can the "label" query go away too, or is that needed still? It would be easier if all instances of singular "label" can go away, instead of most of them

The `label` field on an Annotation or DatasetAnnotation is very deprecated, and really should have been removed a long time ago. It's been superseded by the `labels` field. The reason the `label` field is a problem is that it is a mandatory field, but it is not  present in any data; so if a resolver tries to return an annotation (without the return fields being explicitly specified), it will throw an error when trying to populate the `label` field.
Other uses of the term "Label" relate to a separate object that is not deprecated, and will be present going forward.

**Comment by SJLC** [comment]
Ok too bad, won't be able to validate easily that the updated schema has been properly fixed up by hand.

**Review by SJLC — APPROVED** [review]

**Pull request merged**
